# Generated by Django 5.2.4 on 2025-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
