# Generated by Django 5.2.4 on 2025-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_contacto_telefono_alter_tecnico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='Sin número', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
