# Generated by Django 5.2.4 on 2025-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_contacto_telefono_alter_tecnico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
